//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PRSipl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Datum
    {
        public int Serial_Number { get; set; }
        public string Company { get; set; }
        public string Address { get; set; }
        public string City { get; set; }
        public string First_Name { get; set; }
        public string Last_Name { get; set; }
        public string Mobile_Number { get; set; }
        public string Landline { get; set; }
        public string Email { get; set; }
        public string Sector { get; set; }
        public string Lead_Source { get; set; }
        public string Region { get; set; }
        public string Product { get; set; }
        public string Principal { get; set; }
        public string Designation { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<System.DateTime> Expected_Date { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Probability { get; set; }
        public string Services { get; set; }
        public string Fax { get; set; }
        public string Remarks { get; set; }
    }
}
